#!/usr/bin/env bash
# Generates language-specific realm files from the canonical words/realms.json.
#
# ⚠️ REGENERATING IS NOT A NO-OP — IT RENAMES THINGS IN OTHER PROJECTS.
#
# Indices are `% len(list)`, so adding, removing or REORDERING one word re-maps every seed.
# `words/realms.json` was cut over to lexicon-derived vocabularies on 2026-05-07 (be59e52), but
# go/python/js were never re-synced afterwards and have been frozen since 2026-04-05. So a bare run
# today would not just apply your edit — it would also land three months of accumulated
# `fantasy`/`forge` change into every consumer of those bindings (candela, portal.realm.watch,
# coin.realm.watch, realmwatch), renaming their version names.
#
# Each language is therefore gated, and there is no implicit default:
#
#   ./sync-words.sh --only rust        # one binding (safe — nothing downstream is pinned to it yet)
#   ./sync-words.sh --only go,python   # a chosen subset
#   ./sync-words.sh --all              # everything, INCLUDING the three-month catch-up
#
# `--all` is spelled out rather than assumed precisely because it is the dangerous one.
set -euo pipefail
cd "$(dirname "$0")"

REALMS=words/realms.json
RESERVED=words/reserved.json
WANT=""

usage() {
  cat <<'EOF'
usage: sync-words.sh (--all | --only <langs>)

  --all           regenerate every binding (go, python, js, rust)
  --only <langs>  comma-separated subset: go, python, js, rust

Reads words/realms.json (and words/reserved.json for rust). BOTH are themselves generated from
lexicon.realm.watch by its sync-vocabularies.sh — edit the vocabularies there, not here.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)  WANT="go,python,js,rust"; shift ;;
    --only) WANT="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$WANT" ]]; then
  echo "error: refusing to regenerate implicitly — pass --all or --only <langs>." >&2
  echo "       A bare run would also land the un-synced 2026-05-07 corpus cutover into" >&2
  echo "       go/python/js, renaming version names in every project consuming them." >&2
  usage >&2
  exit 2
fi

want() { [[ ",$WANT," == *",$1,"* ]]; }

echo "Syncing word lists from $REALMS (targets: $WANT)..."

# --- Go: go/realms.go ---
if want go; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['package sigil', '', '// Generated by sync-words.sh — do not edit manually.', '', 'type Realm struct {', '\tAdjectives []string', '\tNouns      []string', '}', '', 'var Realms = map[string]Realm{']

for realm, words in data.items():
    lines.append(f'\t\"{realm}\": {{')
    adjs = ', '.join(f'\"{w}\"' for w in words['adjectives'])
    lines.append(f'\t\tAdjectives: []string{{{adjs}}},')
    nouns = ', '.join(f'\"{w}\"' for w in words['nouns'])
    lines.append(f'\t\tNouns:      []string{{{nouns}}},')
    lines.append('\t},')

lines.append('}')
lines.append('')

with open('go/realms.go', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ go/realms.go')
"
fi

# --- Python: python/realm_sigil/realms.py ---
if want python; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['# Generated by sync-words.sh — do not edit manually.', '', 'REALMS = {']

for realm, words in data.items():
    lines.append(f'    \"{realm}\": {{')
    lines.append(f'        \"adjectives\": {json.dumps(words[\"adjectives\"])},')
    lines.append(f'        \"nouns\": {json.dumps(words[\"nouns\"])},')
    lines.append('    },')

lines.append('}')
lines.append('')

with open('python/realm_sigil/realms.py', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ python/realm_sigil/realms.py')
"
fi

# --- JS: js/realms.js ---
if want js; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['// Generated by sync-words.sh — do not edit manually.', '', 'const REALMS = {']

for realm, words in data.items():
    lines.append(f'  {realm}: {{')
    lines.append(f'    adjectives: {json.dumps(words[\"adjectives\"])},')
    lines.append(f'    nouns: {json.dumps(words[\"nouns\"])},')
    lines.append('  },')

lines.append('};')
lines.append('')
lines.append('module.exports = { REALMS };')
lines.append('')

with open('js/realms.js', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ js/realms.js')
"
fi

# --- Rust: rust/src/realms.rs + rust/src/reserved.rs ---
# The Rust binding is `no_std` with no `alloc` (it compiles into bare-metal firmware), so the corpus
# has to be a static table rather than a map built at startup: `&'static [&'static str]` lands in
# .rodata and costs no heap and no stack. The reserved set ships with it because rust/src/lib.rs
# asserts `vocabulary ∩ reserved == ∅` at COMPILE TIME, and that assertion cannot exist without the
# list. Heredoc rather than `python3 -c "…"` so nothing here depends on escaping quotes correctly.
if want rust; then
python3 - "$REALMS" "$RESERVED" <<'PYEOF'
import json, sys

realms_path, reserved_path = sys.argv[1], sys.argv[2]
with open(realms_path) as f:
    data = json.load(f)

def ident(realm):
    return realm.upper().replace('-', '_')

L = [
    '//! Generated by sync-words.sh from words/realms.json — DO NOT EDIT.',
    '//!',
    '//! Regenerate with `./sync-words.sh --only rust`. Hand-editing a generated corpus is exactly',
    '//! how smol ended up with two copies that drifted from their source with nothing to catch it —',
    '//! the reason this binding exists at all.',
    '',
    'use crate::Realm;',
    '',
]

for realm, words in sorted(data.items()):
    name = ident(realm)
    L.append(f'/// The `{realm}` realm — {len(words["adjectives"])} adjectives / {len(words["nouns"])} nouns.')
    L.append(f'pub static {name}: Realm = Realm {{')
    L.append(f'    name: "{realm}",')
    L.append('    adjectives: &[')
    for w in words['adjectives']:
        L.append(f'        "{w}",')
    L.append('    ],')
    L.append('    nouns: &[')
    for w in words['nouns']:
        L.append(f'        "{w}",')
    L.append('    ],')
    L.append('};')
    L.append('')

L.append('/// Every realm, sorted by name.')
L.append('pub static REALMS: &[&Realm] = &[')
for realm in sorted(data):
    L.append(f'    &{ident(realm)},')
L.append('];')
L.append('')
L.append("/// Look up a realm by name, falling back to `fantasy` for an unknown one — matching Go's")
L.append('/// `GenerateName`, which falls back rather than erroring.')
L.append("pub const fn realm_by_name(name: &str) -> &'static Realm {")
L.append('    let mut i = 0;')
L.append('    while i < REALMS.len() {')
L.append('        if crate::str_eq_ascii_ci(REALMS[i].name, name) {')
L.append('            return REALMS[i];')
L.append('        }')
L.append('        i += 1;')
L.append('    }')
L.append('    &FANTASY')
L.append('}')
L.append('')

with open('rust/src/realms.rs', 'w') as f:
    f.write('\n'.join(L))
print(f'  ✓ rust/src/realms.rs ({len(data)} realms)')

with open(reserved_path) as f:
    res = json.load(f)['reserved']

R = [
    '//! Generated by sync-words.sh from words/reserved.json — DO NOT EDIT.',
    '//!',
    '//! Words that must never name a node, because each already names something else: a mesh ROLE',
    '//! (`crown` IS the gateway role), a wire FRAME, a FEATURE, or a sibling PROJECT. An identity',
    '//! drawn from the same vocabulary as a role is a permanent ambiguity — a board called Crown',
    '//! that is not the crown reads as a contradiction in every log line and dashboard.',
    '//!',
    '//! Source of truth: lexicon.realm.watch/vocabularies/reserved.yaml, which groups these by',
    '//! reason. Consumers only need membership, so this is a flat sorted list.',
    '',
    '/// The reserved words — lower-case, sorted.',
    'pub static RESERVED: &[&str] = &[',
]
for w in res:
    R.append(f'    "{w}",')
R.append('];')
R.append('')

with open('rust/src/reserved.rs', 'w') as f:
    f.write('\n'.join(R))
print(f'  ✓ rust/src/reserved.rs ({len(res)} words)')
PYEOF
fi

echo "Done."
