#!/usr/bin/env bash
# Generates language-specific realm files from the canonical words/realms.json.
#
# ⚠️ REGENERATING IS NOT A NO-OP — IT RENAMES THINGS IN OTHER PROJECTS.
#
# Indices are `% len(list)`, so adding, removing or REORDERING one word re-maps every seed.
# `words/realms.json` was cut over to lexicon-derived vocabularies on 2026-05-07 (be59e52), but
# go/python/js were never re-synced afterwards and have been frozen since 2026-04-05. So a bare run
# today would not just apply your edit — it would also land three months of accumulated
# `fantasy`/`forge` change into every consumer of those bindings (candela, portal.realm.watch,
# coin.realm.watch, realmwatch), renaming their version names.
#
# Each language is therefore gated, and there is no implicit default:
#
#   ./sync-words.sh --only rust        # one binding (safe — nothing downstream is pinned to it yet)
#   ./sync-words.sh --only go,python   # a chosen subset
#   ./sync-words.sh --all              # everything, INCLUDING the three-month catch-up
#
# `--all` is spelled out rather than assumed precisely because it is the dangerous one.
set -euo pipefail
cd "$(dirname "$0")"

REALMS=words/realms.json
RESERVED=words/reserved.json
WANT=""

usage() {
  cat <<'EOF'
usage: sync-words.sh (--all | --only <langs>)

  --all           regenerate every binding (go, python, js, rust)
  --only <langs>  comma-separated subset: go, python, js, rust

Reads words/realms.json (and words/reserved.json for rust). BOTH are themselves generated from
lexicon.realm.watch by its sync-vocabularies.sh — edit the vocabularies there, not here.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)  WANT="go,python,js,rust"; shift ;;
    --only) WANT="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$WANT" ]]; then
  echo "error: refusing to regenerate implicitly — pass --all or --only <langs>." >&2
  echo "       A bare run would also land the un-synced 2026-05-07 corpus cutover into" >&2
  echo "       go/python/js, renaming version names in every project consuming them." >&2
  usage >&2
  exit 2
fi

want() { [[ ",$WANT," == *",$1,"* ]]; }

echo "Syncing word lists from $REALMS (targets: $WANT)..."

# --- Go: go/realms.go ---
if want go; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['package sigil', '', '// Generated by sync-words.sh — do not edit manually.', '', 'type Realm struct {', '\tAdjectives []string', '\tNouns      []string', '}', '', 'var Realms = map[string]Realm{']

for realm, words in data.items():
    lines.append(f'\t\"{realm}\": {{')
    adjs = ', '.join(f'\"{w}\"' for w in words['adjectives'])
    lines.append(f'\t\tAdjectives: []string{{{adjs}}},')
    nouns = ', '.join(f'\"{w}\"' for w in words['nouns'])
    lines.append(f'\t\tNouns:      []string{{{nouns}}},')
    lines.append('\t},')

lines.append('}')
lines.append('')

with open('go/realms.go', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ go/realms.go')
"
fi

# --- Python: python/realm_sigil/realms.py ---
if want python; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['# Generated by sync-words.sh — do not edit manually.', '', 'REALMS = {']

for realm, words in data.items():
    lines.append(f'    \"{realm}\": {{')
    lines.append(f'        \"adjectives\": {json.dumps(words[\"adjectives\"])},')
    lines.append(f'        \"nouns\": {json.dumps(words[\"nouns\"])},')
    lines.append('    },')

lines.append('}')
lines.append('')

with open('python/realm_sigil/realms.py', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ python/realm_sigil/realms.py')
"
fi

# --- JS: js/realms.js ---
if want js; then
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['// Generated by sync-words.sh — do not edit manually.', '', 'const REALMS = {']

for realm, words in data.items():
    lines.append(f'  {realm}: {{')
    lines.append(f'    adjectives: {json.dumps(words[\"adjectives\"])},')
    lines.append(f'    nouns: {json.dumps(words[\"nouns\"])},')
    lines.append('  },')

lines.append('};')
lines.append('')
lines.append('module.exports = { REALMS };')
lines.append('')

with open('js/realms.js', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ js/realms.js')
"
fi

# --- Rust: rust/src/realms.rs + rust/src/reserved.rs ---
# The Rust binding is `no_std` with no `alloc` (it compiles into bare-metal firmware), so the corpus
# has to be a static table rather than a map built at startup: `&'static [&'static str]` lands in
# .rodata and costs no heap and no stack. The reserved set ships with it because rust/src/lib.rs
# asserts `vocabulary ∩ reserved == ∅` at COMPILE TIME, and that assertion cannot exist without the
# list. Heredoc rather than `python3 -c "…"` so nothing here depends on escaping quotes correctly.
if want rust; then
python3 - "$REALMS" "$RESERVED" <<'PYEOF'
import json, re, sys

realms_path, reserved_path = sys.argv[1], sys.argv[2]
with open(realms_path) as f:
    data = json.load(f)

def ident(realm):
    return realm.upper().replace('-', '_')

L = [
    '//! Generated by sync-words.sh from words/realms.json — DO NOT EDIT.',
    '//!',
    '//! Regenerate with `./sync-words.sh --only rust`. Hand-editing a generated corpus is exactly',
    '//! how smol ended up with two copies that drifted from their source with nothing to catch it —',
    '//! the reason this binding exists at all.',
    '',
    'use crate::Realm;',
    '',
]

DIVERGENT_NOTE = (
    '///',
    '/// ⚠️ CORPUS-DIVERGENT from the go/python/js bindings, hence the feature gate. This realm’s',
    '/// words here differ from the generated Go embed, and indices are `% len(list)` — so the same',
    '/// arithmetic over different lists yields a different name for the same hash. A project',
    '/// consuming two bindings would publish two version names for one commit, so this realm is OFF',
    '/// by default.',
    '///',
    '/// Emitted only when the words actually differ. If you are reading this, run',
    '/// `./sync-words.sh --all` to converge every binding, or accept the gate deliberately.',
)

THEMED_NOTE = (
    '///',
    '/// Gated: this realm names a **build**, not a thing. Its words currently agree with the',
    '/// go/python/js embeds, but that agreement is a maintained property rather than a structural',
    '/// one, so reaching it requires writing `divergent-themed-realms` into a Cargo.toml where a',
    '/// reviewer sees it. The static is not merely hidden — it is not emitted at all without the',
    '/// feature, so a default build carries none of these words in `.rodata`, which matters to the',
    '/// firmware consumers this binding exists for.',
)

# Which realms are corpus-divergent from the other bindings? DERIVED, not listed: a realm can only
# disagree with go/python/js if those bindings HAVE it. A realm absent from the (frozen) generated Go
# embed exists nowhere else, so nothing can contradict it and it needs no gate. Deriving this means
# every future identity-style namespace is automatically ungated, and nobody has to remember to add
# it — a hardcoded `!= 'fleet'` would have silently gated `creature` the day it landed.
#
# ⚠️ Presence is NOT divergence, and testing presence broke `--all`.
#
# `--all` regenerates go/realms.go *before* rust, from this same words/realms.json. So by the time
# this ran, every realm appeared in the Go embed — including `fleet` and `creature`, which had been
# ungated precisely because Go lacked them — and all nine got gated behind
# `divergent-themed-realms`. `lib.rs` references `realms::FLEET` and `realms::CREATURE`
# unconditionally, so the crate stopped compiling: "cannot find value `FLEET` in module `realms`,
# note: found an item that was configured out".
#
# Worse, the gate's premise had become false. Two bindings generated from one source cannot
# disagree, so after a full sync the divergent set is empty by construction.
#
# So compare CONTENT, not presence. This keeps the derived-not-listed property that makes future
# namespaces automatically correct, and restores the meaning the gate was written to carry — which
# still matters for a partial sync like `--only rust`, the case it was designed for.
# `go/realms.go` is TRACKED. An absent one means this run is wrong — bad cwd, partial checkout —
# not that nothing can diverge. Folding that UNKNOWN into "not divergent" would ungate every realm
# while printing success: a gate that cannot say "I could not tell" eventually says "fine" when it
# means "I did not look". So it is a hard error, distinct from a realm genuinely absent from the
# embed (which `_go_words` still reports as None, and which really does mean nothing can contradict
# it).
try:
    go_embed = open('go/realms.go').read()
except FileNotFoundError:
    sys.exit(
        'go/realms.go is missing, so the divergence gate cannot be derived. Refusing to generate '
        'an ungated corpus on a guess — run from a full checkout.'
    )

def _go_words(realm):
    """Adjectives + nouns for `realm` as they appear in the generated Go embed."""
    block = re.search(
        r'"%s":\s*\{(.*?)\n\t\},' % re.escape(realm), go_embed, re.S
    )
    if not block:
        return None
    return re.findall(r'"([^"]*)"', block.group(1))

def is_divergent(realm):
    theirs = _go_words(realm)
    if theirs is None:
        return False  # absent there: nothing can contradict it
    ours = list(data[realm]['adjectives']) + list(data[realm]['nouns'])
    return theirs != ours

# Which realms may a consumer reach WITHOUT writing the hazard into its Cargo.toml?
#
# Only the IDENTITY realms — the ones naming a *thing* (a board, a familiar) rather than a *build*.
# That is a taxonomy, and a taxonomy is curated rather than derived: nothing in words/realms.json
# marks a realm as identity-or-themed, and the signal that used to stand in for it is gone.
#
# ⚠️ The old criterion — "exists in no other binding, so nothing can contradict it" — EXPIRED on
# 2026-07-29, when `--all` wrote `fleet` and `creature` into go/python/js. Every realm now exists in
# every binding, so presence selects the EMPTY set, and it cannot be revived by comparing against
# the Go embed because `--all` regenerates that embed before this runs (the 7cd4e46 bug). The
# premise moved and the conclusion did not: the default list silently widened from two realms to
# nine, and `REALMS` began handing out `&FORGE` to callers that `lib.rs` refuses to give `FORGE`.
#
# Listing the taxonomy therefore FAILS CLOSED: a realm added upstream is themed until someone says
# otherwise, so a new build-provenance realm cannot leak by omission. A new IDENTITY realm omitted
# here fails loudly instead — absent from the default `REALMS`, its consumer stops compiling.
IDENTITY_REALMS = {'creature', 'fleet'}

for realm, words in sorted(data.items()):
    name = ident(realm)
    divergent = is_divergent(realm)
    # Gate a realm if it names a build, OR if its words have drifted from the Go embed. The second
    # is the tripwire a partial sync trips; the first is the standing rule. Both produce the same
    # `#[cfg]`, so a themed realm that also goes divergent is gated once, not twice.
    themed = realm not in IDENTITY_REALMS
    L.append(f'/// The `{realm}` realm — {len(words["adjectives"])} adjectives / {len(words["nouns"])} nouns.')
    if divergent:
        L.extend(DIVERGENT_NOTE)
    elif themed:
        L.extend(THEMED_NOTE)
    if divergent or themed:
        L.append('#[cfg(feature = "divergent-themed-realms")]')
    L.append(f'pub static {name}: Realm = Realm {{')
    L.append(f'    name: "{realm}",')
    L.append('    adjectives: &[')
    for w in words['adjectives']:
        L.append(f'        "{w}",')
    L.append('    ],')
    L.append('    nouns: &[')
    for w in words['nouns']:
        L.append(f'        "{w}",')
    L.append('    ],')
    L.append('};')
    L.append('')

L.append('/// EVERY realm, sorted by name — the identity realms plus the themed, build-provenance')
L.append('/// ones. Reachable only with `divergent-themed-realms`; the default list below is the')
L.append('/// identity subset.')
L.append('#[cfg(feature = "divergent-themed-realms")]')
L.append('pub static REALMS: &[&Realm] = &[')
for realm in sorted(data):
    L.append(f'    &{ident(realm)},')
L.append('];')
L.append('')
default_realms = sorted(r for r in data if r in IDENTITY_REALMS and not is_divergent(r))
if not default_realms:
    sys.exit(
        'no identity realm survived the divergence check, so the default build would expose no '
        'realm at all. Converge the bindings with `--all` before regenerating rust.'
    )
L.append('/// Without `divergent-themed-realms`, only the IDENTITY realms are handed out — the ones')
L.append('/// naming a *thing* (a board, a familiar) rather than a *build*. A themed realm reached')
L.append('/// from here would be a version name acquired without the Cargo.toml declaration that')
L.append('/// makes the hazard visible to a reviewer, which is the entire point of the gate.')
L.append('///')
L.append('/// ⚠️ NOT "realms that exist in no other binding". That was the criterion until')
L.append('/// 2026-07-29, when `--all` wrote `fleet` and `creature` into go/python/js — every realm')
L.append('/// now exists in all four bindings, so these two can diverge like any other. What keeps')
L.append('/// them default is what they NAME; the derived content check below still gates them if')
L.append('/// their words drift from the Go embed.')
L.append('#[cfg(not(feature = "divergent-themed-realms"))]')
L.append('pub static REALMS: &[&Realm] = &[')
for realm in default_realms:
    L.append(f'    &{ident(realm)},')
L.append('];')
L.append('')
L.append("/// Look up a realm by name, falling back to `fantasy` for an unknown one — matching Go's")
L.append('/// `GenerateName`, which falls back rather than erroring.')
L.append('///')
L.append('/// ⚠️ Only available with `divergent-themed-realms`. A name-based lookup is exactly how a')
L.append('/// mixed-language project would silently acquire a divergent version name — it asks for')
L.append('/// "fantasy" in two languages and gets two different answers. Without the feature no themed')
L.append('/// realm is reachable at all — not through this function and not through `REALMS` — so the')
L.append('/// mistake is unrepresentable rather than documented. Use [`FLEET`](crate::FLEET) directly')
L.append('/// for node identity.')
L.append('#[cfg(feature = "divergent-themed-realms")]')
L.append("pub const fn realm_by_name(name: &str) -> &'static Realm {")
L.append('    let mut i = 0;')
L.append('    while i < REALMS.len() {')
L.append('        if crate::str_eq_ascii_ci(REALMS[i].name, name) {')
L.append('            return REALMS[i];')
L.append('        }')
L.append('        i += 1;')
L.append('    }')
L.append('    &FANTASY')
L.append('}')
L.append('')

with open('rust/src/realms.rs', 'w') as f:
    f.write('\n'.join(L))
print(f'  ✓ rust/src/realms.rs ({len(data)} realms)')

with open(reserved_path) as f:
    res = json.load(f)['reserved']

R = [
    '//! Generated by sync-words.sh from words/reserved.json — DO NOT EDIT.',
    '//!',
    '//! Words that must never name a node, because each already names something else: a mesh ROLE',
    '//! (`crown` IS the gateway role), a wire FRAME, a FEATURE, or a sibling PROJECT. An identity',
    '//! drawn from the same vocabulary as a role is a permanent ambiguity — a board called Crown',
    '//! that is not the crown reads as a contradiction in every log line and dashboard.',
    '//!',
    '//! Source of truth: lexicon.realm.watch/vocabularies/reserved.yaml, which groups these by',
    '//! reason. Consumers only need membership, so this is a flat sorted list.',
    '',
    '/// The reserved words — lower-case, sorted.',
    'pub static RESERVED: &[&str] = &[',
]
for w in res:
    R.append(f'    "{w}",')
R.append('];')
R.append('')

with open('rust/src/reserved.rs', 'w') as f:
    f.write('\n'.join(R))
print(f'  ✓ rust/src/reserved.rs ({len(res)} words)')
PYEOF
fi

echo "Done."
